// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /*
     public static final class DriveConstants {
       public static final int[] kLeftEncoderPorts = new int[] {0, 1};
       public static final int[] kRightEncoderPorts = new int[] {2, 3};
       public static final boolean kLeftEncoderReversed = false;        //// dependent on which motors are reverse, needs to be revised
       public static final boolean kRightEncoderReversed = true;        //// dependent on which motors are reverse, needs to be revised
     
       public static final int KEncoderCPR = 1024;
	    public static final double kWheelDiameterInches = __________ ;	
 	    public static final double kEncoderDistancePerPulse = (kWheelDiameterInches * Math.PI) / (double)kEncoderCPR;
     }
    */ 
   // boolean KGyroReversed = false;
}

